services:
  jamixdiscordbot:
    image: jamixdiscordbot
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./config:/app/config
